---
title: "Memoria técnica"
format: html
editor: visual
---

## Antes

Se empezó por descargar los datos brindados a traves del siguiente enlace: https://drive.google.com/drive/folders/1bz5JUa15XU3jQ6HVF7G4jgf5EOwPSjwW?usp=sharing . Posterior a esto se revisaron los mismos para entender qué contenía cada archivo. Se notó que teniamos archivos en formato .xlsx y .zip, para los segundos fue necesario descargarlos y descomprimirlos. Ya con esto hecho, teniamos nuestros datos listos.

Para la selección de qué datos usar procedimos a tener una conversación en el grupo para ver qué variables eran de interés y cuáles podían servir para responder las preguntas sobre las estaciones en los distintos puntos del país. Debido a la gran cantidad de variables existentes se decidió tomar tres grupos:

-   Datos sobre el aprovechamiento forestal

-   Datos sobre la atención a denuncias

-   Datos sobre el origen y destino de los recursos forestales

Por último, se decidió usar el lenguaje de programación R para trabajar. Los scripts, datos y resultados se pueden observar en el siguiente repositorio de GitHub https://github.com/ergostats/actuo_por_los_bosques.git .

## Durante

En la etapa previa, se utilizó los recursos de datos en cuanto a la información geográfica para examinar diversos aspectos relacionados con los recursos forestales: puestos de control de recursos madereros y no madereros, las denuncias atendidas en cuanto al volumen de retención y sobre el origen y destino de estos recursos.

Al aplicar estos recursos se extrajo las capas de información de acuerdo con variables de interés debido a su pertinencia para los puntos de control que son relevantes. Respecto al aprovechamiento forestal, se analizó el área total de los predios y de los programas de protección por provincias, cantones y parroquias. En cuanto a la atención de denuncias, se realicé en cuanto a la cantidad y el total del volumen retenido en los distintos niveles geográficos mencionados anteriormente. Para el origen y destino de los recursos se tomó la frecuencia y las retenciones de estos recursos en sus entradas y salidas. Esta aplicación de los recursos permitió obtener una visión más completa de la situación de los bosques y los recursos madereros y no madereros, así como de las denuncias relacionadas.

Esto para aportar a los resultados deseados y poderlos representarlos de manera grafica a traves de capas geograficas. La información obtenida ayudo a comprender la distribución espacial de los recursos, identificar áreas críticas o en riesgo, optimizar la ubicación de los puestos de control y mejorar la gestión y protección de los bosques.

## 
