---
title: "Descripcion de las matrices"
format: html
editor: visual
---

## Lectura de las bases

```{r}
library(readxl)
library(tidyverse)
library(sf)
library(janitor)
library(stringdist)
library(fuzzyjoin)
```

Lectura del shapefile:

```{r}

shape <- read_sf("data/ORGANIZACION_TERRITORIAL_PARROQUIAL/ORGANIZACION_TERRITORIAL_PARROQUIAL.shp")

dpa <- shape %>%
  as_tibble() %>% 
  select(matches("DPA"))


dpa <- dpa %>% 
  clean_names() %>% 
  mutate(join_var_can = str_c(dpa_despro, dpa_descan, sep = "-"),
         join_var_par = str_c(dpa_despro, dpa_descan, dpa_despar, sep = "-"))


```

Base de datos del aprovechamiento forestal del 2022:

```{r}
tabla_aprovechamiento <- read_excel('data/INSUMOS ESTADISTICOS/MAATE_BDD_aprovechamiento_forestal_2022.xlsx')


tabla_aprovechamiento <- tabla_aprovechamiento %>% 
  clean_names()

tabla_aprovechamiento <- tabla_aprovechamiento %>% 
  group_by(provincia, canton, parroquia) %>% 
  summarise(suma_area_predio = sum(area_del_predio_has, na.rm = T),
            suma_area_programa = sum(area_del_programa_has, na.rm = T))

tabla_aprovechamiento <- tabla_aprovechamiento %>% 
  mutate(join_var_can = str_c(provincia, canton , sep = "-"))

tabla_aprovechamiento <- stringdist_left_join(x = dpa,y = tabla_aprovechamiento)
```

Base de datos de la atencion a denuncias de talas del 2022:

```{r}
tabla_denuncias<-read_excel('data/INSUMOS ESTADISTICOS/MAATE_BDD_atencion_denuncias_talas_2022.xlsx')


tabla_denuncias<-tabla_denuncias %>%
  clean_names()

tabla_denuncias %>% 
  group_by(canton) %>%
  summarise(denuncias=n(),
            suma_vol_retenido = sum(volumen_retenido,na.rm = T))

```

Base de datos del destino final de los recursos para el 2022:

```{r}
read_excel('data/INSUMOS ESTADISTICOS/MAATE_BDD_destino_final_2022.xlsx')
```

Base de datos de los puestos fijos de control para el 2022:

```{r}
tabla_puestos <- read_excel('data/INSUMOS ESTADISTICOS/MAATE_BDD_puestos_fijos_2022.xlsx')

tabla_puestos <- tabla_puestos %>% 
  clean_names() 
```

Base de datos de las unidades moviles de control para el 2022:

```{r}
read_excel('data/INSUMOS ESTADISTICOS/MAATE_BDD_unidades_moviles_2022.xlsx')
```

Shape file:

```{r}

```

Limpieza shape:

```{r}

origen <- tabla_puestos %>% 
  group_by(origen, origen_provincia) %>% 
  summarise(frecuencia = n(),
            cubicado = sum(cubicado_vtotal, na.rm = T),
            retencion = sum(vol_ret,na.rm = T))

origen <- origen %>% 
  mutate(join_var_can = str_c( origen_provincia,origen, sep = "-"))

origen <- stringdist_left_join(x = dpa,y = origen)


```

```{r}
shape %>% 
  ggplot() +
  geom_sf()
```
